//#define USE_LENS_UNDISTORT
#define PROJECT_METHOD cv::detail::SphericalWarper

//#define USE_ALIGN_PROCESSOR
//#define USE_EXTERNAL_CALIBRATION_FILE
#define OUTPUT_FULL_PANO 0
#define OUTPUT_PARTIAL_PANO 1
#define STRATEGY_OUTPUT OUTPUT_FULL_PANO
#define RANSAC_REPROJ_THRES 3.0

#define BLEND_THRESHOLD 150
#define INNER_LAYER_RATIO_H 0.028
#define CARE_TIME
