//#define USE_LENS_UNDISTORT
#define PROJECT_METHOD cv::detail::SphericalWarper

//#define USE_ALIGN_PROCESSOR
//#define USE_EXTERNAL_CALIBRATION_FILE
#define OUTPUT_FULL_PANO 0
#define OUTPUT_PARTIAL_PANO 1
#define STRATEGY_OUTPUT OUTPUT_FULL_PANO

#define RANSAC_REPROJ_THRES 3.0
#define REAL_TIME_STREAMING
#define USING_SERIALIZABLE_RESULT
//#define USE_SALIENCY_MAP_HANDLER
//#define USE_HOMOGRAPHY_WARP
#define CARE_TIME