//#define USE_LENS_UNDISTORT
#define PROJECT_METHOD cv::detail::SphericalWarper

#define VIDEO_CONTAINER_SIZE 100

#define OUTPUT_PANO_WIDTH 2160
#define OUTPUT_PANO_HEIGHT 1080

//#define OUTPUT_PANO_WIDTH 240
//#define OUTPUT_PANO_HEIGHT 120

//#define OUTPUT_PANO_WIDTH 1440
//#define OUTPUT_PANO_HEIGHT 720

//#define OUTPUT_PANO_WIDTH 960
//#define OUTPUT_PANO_HEIGHT 720
//#define OUTPUT_PANO_WIDTH 1920
//#define OUTPUT_PANO_HEIGHT 1440
//#define OUTPUT_PANO_WIDTH 4096
//#define OUTPUT_PANO_HEIGHT 2160

#define DOWN_SAMPLE_MAP_WIDTH 480
#define DOWN_SAMPLE_MAP_HEIGHT 240

//#define USE_ALIGN_PROCESSOR
//#define USE_EXTERNAL_CALIBRATION_FILE
#define OUTPUT_FULL_PANO 0
#define OUTPUT_PARTIAL_PANO 1
#define STRATEGY_OUTPUT OUTPUT_FULL_PANO

#define RANSAC_REPROJ_THRES 3.0
#define REAL_TIME_STREAMING
#define USING_SERIALIZABLE_RESULT
//#define USE_HOMOGRAPHY_WARP
#define CARE_TIME
//#define USING_UDP