//#define USE_LENS_UNDISTORT
#define PROJECT_METHOD cv::detail::MercatorWarper

//#define USE_ALIGN_PROCESSOR
#define USE_EXTERNAL_CALIBRATION_FILE
#define USE_EXPOSURE_COMPENSATOR
#define USE_BLENDER
#define USE_SMALLER_CANVAS 4

/*
#define SURF_MIN_HESSIAN 400
#define MATCH_NNDRRATIO 0.6667
#define RANSAC_REPROJ_THRES 3.0
*/