#define OUTPUT_PANO_WIDTH 2000
#define OUTPUT_PANO_HEIGHT 1000
//#define THRESHOLD_THETA M_PI/4
//#define THRESHOLD_PHI M_PI/8
#define THRESHOLD_THETA M_PI/2
#define THRESHOLD_PHI M_PI/3
#define PROJECT_CIRCLE_LEN 1.f

#define SURF_MIN_HESSIAN 400
#define MATCH_NNDRRATIO 0.6667
#define RANSAC_REPROJ_THRES 3.0